BritishAcademy/Controllers/AdminManageAccountController.cs
//using BC =BCrypt.Net.BCrypt;
using BritishAcademy.Data;
using BritishAcademy.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System.Linq;
using System.Threading.Tasks;


namespace AdminManageAccount.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminManageAccontController : Controller
    {
    
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AdminManageAccontController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
        
            _userManager = userManager;
            _context = context;
            _roleManager = roleManager;
        

        }
        // GET: AdminManageAcconts
        public IActionResult Index(string UserName, int? page)
        {
           

            var res = _context.Users.Where(x => x.Email.Equals(null));
            var Qr = res.Select(x => new ApplicationUser
            {
                Id = x.Id,
                Name = x.Name,
                PhoneNumber = x.PhoneNumber,
                //Address = x.Address,
                //Gender = x.Gender,
                UserName = x.UserName,
                //Email = x.Email,
                //Birthdate = x.Birthdate

            });

            if (!string.IsNullOrEmpty(UserName))
            {
                Qr = Qr.Where(x => x.UserName == UserName);
            }
        
            return View(Qr.OrderBy(s => s.Id).ThenByDescending(s => s.UserName).ToPagedList(page ?? 1, 10));
           
        }

        // GET: AdminManageAcconts/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _userManager.FindByIdAsync(id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: AdminManageAcconts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminManageAcconts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
            

                var s = new ApplicationUser
                {
                    Name = applicationUser.Name,
                    PhoneNumber = applicationUser.PhoneNumber,
                    //Address = applicationUser.Address,
                    //Birthdate = applicationUser.Birthdate,
                    
                    //Email = applicationUser.Email,
             

                    UserName = (applicationUser.Name).Substring(0, 3) + "_" + (applicationUser.PhoneNumber).Substring(1, 5),
             
                    //Gender = applicationUser.Gender
                };
        
                await _userManager.CreateAsync(s, (applicationUser.Name).Substring(0, 3) + "_" + (applicationUser.PhoneNumber).Substring(1, 5));
           
                await _userManager.AddToRoleAsync(s, "Student");
      
                return RedirectToAction("Index");

            }
            else
            {
                return View();
            }
        }

        // GET: AdminManageAcconts/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _userManager.FindByIdAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            return View(account);
        }

        // POST: AdminManageAcconts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, ApplicationUser application)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    user.Name = application.Name;
                    user.UserName = application.UserName;
                    //user.Email = application.Email;
                    user.PhoneNumber = application.PhoneNumber;
                    //user.Address = application.Address;
                    //user.Birthdate = application.Birthdate;
                    //user.Gender = application.Gender;


                    user.UserName = (application.Name).Substring(0, 3) + "_" + (application.PhoneNumber).Substring(1, 5);
                    await _userManager.UpdateAsync(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: AdminManageAcconts/Delete/5
        //public async Task<ActionResult> Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var account = await _userManager.FindByIdAsync(id);
        //    if (account == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(account);
        //}

        //// POST: AdminManageAcconts/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConformed(string id)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here
        //        var account = await _userManager.FindByIdAsync(id);
        //        await _userManager.DeleteAsync(account);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
       


    }
}

BritishAcademy/Views/AdminManageAccont/Create.cshtml
@model BritishAcademy.Models.ApplicationUser


<div style="margin:60px;">


    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <h4 style="color:saddlebrown;">Create a new account</h4>
                <hr />
                @*<div asp-validation-summary="All" class="text-danger"></div>*@
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
                @*<div class="form-group">
                   
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control"  type="email"/>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                 
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" min="6" required  />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                @*<div class="form-group">
                  
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>*@
                @*<div class="form-group">
                   
                    <label asp-for="Birthdate" class="control-label"></label>
                    <input asp-for="Birthdate" class="form-control" />
                    <span asp-validation-for="Birthdate" class="text-danger"></span>
                </div>*@
                @*<div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                
                    <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>*@

                <button type="submit" class="btn btn-dark" style="background-color:saddlebrown;">Create</button>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BritishAcademy/Views/AdminManageAccont/Edit.cshtml
@model BritishAcademy.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit";
}

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <h4 style="color:saddlebrown;">Edit Information</h4>
                    <hr />
                    @*<div asp-validation-summary="All" class="text-danger"></div>*@
                    <div class="form-group">
                        <p asp-for="Name" style="text-align:left">Name</p>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                        <p asp-for="Email" style="text-align:left">Email</p>
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>*@
                    <div class="form-group">
                        <p asp-for="PhoneNumber" style="text-align:left">Phone Number</p>
                        @*<label asp-for="PhoneNumber"></label>*@
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                        <p asp-for="Address" style="text-align:left">Address</p>
                        <label asp-for="Address"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <p asp-for="Birthdate" style="text-align:left">Birthdate</p>
                        <label asp-for="Birthdate" class="control-label"></label>
                        <input asp-for="Birthdate" class="form-control" />
                        <span asp-validation-for="Birthdate" class="text-danger"></span>
                    </div>*@
                    @*<div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <p asp-for="Gender" style="text-align:left">Gender</p>
                        <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>*@

                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-dark" style="background-color:saddlebrown;" /> | <a asp-action="Index">Back to list</a>
                    </div>
                </form>
            </div>
        </div>





    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BritishAcademy/Views/AdminManageAccont/Index.cshtml
@{
    ViewData["Title"] = "View";
}

@model IEnumerable<BritishAcademy.Models.ApplicationUser>

    <div class="container">
        <p>
            <h2 style="text-align:left;color:saddlebrown;">
                STUDENTS |<a class="btn btn-dark" style="background-color:saddlebrown;" asp-area="" asp-controller="AdminManageAccont" asp-action="Create">New Account</a>



            </h2>
        </p>

        <div class="row">
            <div class="col-md-4">
                <p>
                    <form class="form-inline" role="form" dir="ltr">
                        <div class="form-group">
                            <label class="sr-only"></label>
                            <input type="text" class="form-control" name="UserName" placeholder="User Name">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-dark" style="background-color:saddlebrown;margin-right:5px;">
                                Search
                            </button>
                            <a href="@Url.Action("index")" class="btn btn-dark" style="background-color:saddlebrown;">All</a>
                        </div>
                    </form>
                </p>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UserName)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)

                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gender)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Birthdate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>*@
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gender)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Birthdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>*@
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                    </svg>
                                </a>
                                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |*@
                                @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <hr />
        <div class="row">
            <partial name="_PagedList" />
        </div>


    </div>