BritishAcademy/Controllers/CertficateUploadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BritishAcademy.Data;
using BritishAcademy.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using PagedList.Core;
using Microsoft.AspNetCore.Authorization;

namespace BritishAcademy.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CertficateUploadsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CertficateUploadsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CertficateUploads
        public IActionResult Index(int? page)
        {


            var data = _context.CertficateUploads.AsQueryable();
            var data2 = data.Select(s => new showModel
            {
                ID = s.Id,
                Course = s.Course.Title,
                UserName = s.ApplicationUser.UserName,
                Student = s.ApplicationUser.Name,
                Certificate = s.Name,
                Extension = s.Extension,
                FileType = s.FileType,
                Description = s.Description,
                CreatedOn = s.CreatedOn

            });
            return View(data2.OrderBy(x => x.ID).ThenByDescending(s => s.UserName).ToPagedList(page ?? 1, 10)); ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadToDatabase(List<IFormFile> files, string description , CertficateUpload certficateUpload)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in files)
                {
                    var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                    var extension = Path.GetExtension(file.FileName);
                    var fileModel = new CertficateUpload
                    {
                        CreatedOn = DateTime.Now,
                        FileType = file.ContentType,
                        Extension = extension,
                        Name = fileName,
                        Description = description,
                        CourseID = certficateUpload.CourseID,
                        ApplicationUserId = certficateUpload.ApplicationUserId
                    };
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        fileModel.Data = dataStream.ToArray();
                    }
                    _context.CertficateUploads.Add(fileModel);
                    //  _context.Add(certficateUpload);
                    _context.SaveChanges();
                }
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "UserName", certficateUpload.ApplicationUserId);
            ViewData["CourseID"] = new SelectList(_context.Courses, "Id", "Title", certficateUpload.CourseID);
            TempData["Message"] = "File successfully uploaded to Database";
            return RedirectToAction("Index");
        }

        // GET: CertficateUploads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var certficateUpload = await _context.CertficateUploads
                .Include(c => c.ApplicationUser)
                .Include(c => c.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (certficateUpload == null)
            {
                return NotFound();
            }

            return View(certficateUpload);
        }

        // GET: CertficateUploads/Create
        public IActionResult Create()
        {
           
            ViewData["ApplicationUserId"] = new SelectList(_context.Users.Where(x => x.Email.Equals(null)), "Id", "UserName");

            ViewData["CourseID"] = new SelectList(_context.Courses, "Id", "Title");
            return View();
        }

        // POST: CertficateUploads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Data,CourseID,ApplicationUserId,Id,Name,FileType,Extension,Description,CreatedOn")] CertficateUpload certficateUpload)
        {
            if (ModelState.IsValid)
            {
                _context.Add(certficateUpload);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", certficateUpload.ApplicationUserId);
            ViewData["CourseID"] = new SelectList(_context.Courses, "Id", "Id", certficateUpload.CourseID);
            return View(certficateUpload);
        }

        // GET: CertficateUploads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var CertficateUploads = await _context.CertficateUploads.FindAsync(id);
            if (CertficateUploads == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users.Where(x => x.PhoneNumber.Contains("7")), "Id", "UserName");

            ViewData["CourseID"] = new SelectList(_context.Courses, "Id", "Title");
            return View(CertficateUploads);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, List<IFormFile> files, string description, CertficateUpload certficateUpload)
        {
            if (id != certficateUpload.Id)
            {
                return NotFound();
            }
         
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var file in files)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        var extension = Path.GetExtension(file.FileName);
                        var fileModel = new CertficateUpload
                        {
                            CreatedOn = DateTime.UtcNow,
                            FileType = file.ContentType,
                            Extension = extension,
                            Name = fileName,
                            Description = description,
                            CourseID = certficateUpload.CourseID,
                            ApplicationUserId = certficateUpload.ApplicationUserId
                        };
                        using (var dataStream = new MemoryStream())
                        {
                            await file.CopyToAsync(dataStream);
                            fileModel.Data = dataStream.ToArray();
                        }
                        _context.Update(certficateUpload);
                        await _context.SaveChangesAsync();

                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CertficateUploadsExists(certficateUpload.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "UserName", certficateUpload.ApplicationUserId);
            ViewData["CourseID"] = new SelectList(_context.Courses, "Id", "Title", certficateUpload.CourseID);
            TempData["Message"] = "File successfully uploaded to Database";
            return RedirectToAction("Index");
        }

        // POST: CertficateUploads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.


        // GET: CertficateUploads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var certficateUpload = await _context.CertficateUploads
                .Include(c => c.ApplicationUser)
                .Include(c => c.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (certficateUpload == null)
            {
                return NotFound();
            }

            return View(certficateUpload);
        }

        // POST: CertficateUploads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var certficateUpload = await _context.CertficateUploads.FindAsync(id);
            _context.CertficateUploads.Remove(certficateUpload);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CertficateUploadExists(int id)
        {
            return _context.CertficateUploads.Any(e => e.Id == id);
        }

    

        private bool CertficateUploadsExists(int id)
        {
            return _context.CertficateUploads.Any(e => e.Id == id);
        }

        public async Task<IActionResult> DeleteFileFromDatabase(int id)
        {

            var file = await _context.CertficateUploads.Where(x => x.Id == id).FirstOrDefaultAsync();
            _context.CertficateUploads.Remove(file);
            _context.SaveChanges();

BritishAcademy/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BritishAcademy.Data;
using BritishAcademy.Models;

namespace BritishAcademy.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Duration")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Duration")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
    }
}

BritishAcademy/Controllers/StudentsCertificatesController.cs
using System;
using System.Collections.Generic;

using System.Linq;
using System.Threading.Tasks;
using BritishAcademy.Data;
using BritishAcademy.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BritishAcademy.Controllers
{
    public class StudentsCertificatesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsCertificatesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string UserName )
        {
            
            var data = _context.CertficateUploads.AsQueryable();
            var Qr = data.Select(s => new showModel
            {
                ID = s.Id,
                Course = s.Course.Title,
                UserName = s.ApplicationUser.UserName,
                Student = s.ApplicationUser.Name,
                Certificate = s.Name,
                Description = s.Description,
            });

            if (!string.IsNullOrEmpty(UserName))
            {
                Qr = Qr.Where(x => x.UserName == UserName);
             
                TempData["Message"] = UserName;
                ViewBag.Message = TempData["Message"];
            }
 
         
            return View(Qr.OrderBy(x => x.ID));

        }

        public async Task<IActionResult> DownloadFileFromDatabase(int id)
        {

            var file = await _context.CertficateUploads.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            return File(file.Data, file.FileType, file.Name + file.Extension);
        }
    }
}

BritishAcademy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AUSTRALIA ACADEMY</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family:Rockwell;font-size:21px;">
                    <img src="~/lib/logo.png" alt="5 Terre" style="width: 70px;padding-right:10px;">Australia Academy
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminManageAccont" asp-action="Index">Students </a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="CertficateUploads" asp-action="Index">Certificates </a>
                            </li>
                        }
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses </a>
                        </li>

                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentsCertificates" asp-action="Index">Students Certificates </a>
                        </li>
                        @if (User.IsInRole("Super Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>}

                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>
    <br /><br />



    <footer id="footer">
        <div class="top-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding text-white">About Us</h4>
                        </div>
                        <div class="info-sec">
                            <p>
                                Australia <br />
                                Queensland-Caloundra City <br />
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                                    <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z" />
                                    <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                </svg> St: central park dr <br />
                                Beside Aussie environmental

                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding text-white">Quick Links</h4>
                        </div>
                        <div class="info-sec">
                            <a class="nav-link text-white" asp-area="" asp-controller="StudentsCertificates" asp-action="Index">
                                Students Cetrtificates
                            </a>
                            <a class="nav-link text-white" asp-area="" asp-controller="Courses" asp-action="Index">Courses </a>

                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding text-white">Contact us</h4>
                        </div>
                        <div class="info-sec">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
                                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z" />
                                </svg> +919501979971 <b>-</b> +8801404365286
                            </p>
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-line" viewBox="0 0 16 16">
                                    <path d="M8 0c4.411 0 8 2.912 8 6.492 0 1.433-.555 2.723-1.715 3.994-1.678 1.932-5.431 4.285-6.285 4.645-.83.35-.734-.197-.696-.413l.003-.018.114-.685c.027-.204.055-.521-.026-.723-.09-.223-.444-.339-.704-.395C2.846 12.39 0 9.701 0 6.492 0 2.912 3.59 0 8 0ZM5.022 7.686H3.497V4.918a.156.156 0 0 0-.155-.156H2.78a.156.156 0 0 0-.156.156v3.486c0 .041.017.08.044.107v.001l.002.002.002.002a.154.154 0 0 0 .108.043h2.242c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157Zm.791-2.924a.156.156 0 0 0-.156.156v3.486c0 .086.07.155.156.155h.562c.086 0 .155-.07.155-.155V4.918a.156.156 0 0 0-.155-.156h-.562Zm3.863 0a.156.156 0 0 0-.156.156v2.07L7.923 4.832a.17.17 0 0 0-.013-.015v-.001a.139.139 0 0 0-.01-.01l-.003-.003a.092.092 0 0 0-.011-.009h-.001L7.88 4.79l-.003-.002a.029.029 0 0 0-.005-.003l-.008-.005h-.002l-.003-.002-.01-.004-.004-.002a.093.093 0 0 0-.01-.003h-.002l-.003-.001-.009-.002h-.006l-.003-.001h-.004l-.002-.001h-.574a.156.156 0 0 0-.156.155v3.486c0 .086.07.155.156.155h.56c.087 0 .157-.07.157-.155v-2.07l1.6 2.16a.154.154 0 0 0 .039.038l.001.001.01.006.004.002a.066.066 0 0 0 .008.004l.007.003.005.002a.168.168 0 0 0 .01.003h.003a.155.155 0 0 0 .04.006h.56c.087 0 .157-.07.157-.155V4.918a.156.156 0 0 0-.156-.156h-.561Zm3.815.717v-.56a.156.156 0 0 0-.155-.157h-2.242a.155.155 0 0 0-.108.044h-.001l-.001.002-.002.003a.155.155 0 0 0-.044.107v3.486c0 .041.017.08.044.107l.002.003.002.002a.155.155 0 0 0 .108.043h2.242c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157H11.81v-.589h1.525c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157H11.81v-.589h1.525c.086 0 .155-.07.155-.156Z" />
                                </svg> +61423874671
                            </p>
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                                </svg> info@academy-australia.com
                            </p>


                        </div>

                    </div>




                    </div>
                </div>
        </div>
        <div class="footer-line">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        © Copyright AAIPS. All Rights Reserved
                     
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="html2pdf.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

BritishAcademy/Views/Shared/_PagedList.cshtml
@{
    ViewData["Title"] = "_PagedList";
}



@model PagedList.Core.IPagedList
@using PagedList.Core.Mvc


<div class="row">
    <div class="col-sm-12 col-md-7" >
        <pager  class="page-item"   list="@Model"
               options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext"
               asp-action="@ViewContext.RouteData.Values["Action"]"
               param-page-number="page"  />

    </div>
    <div class="col-sm-12 col-md-5">
        <div class="dataTables_info float-right"></div>
    </div>
</div>